/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author DK_Roshan
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentsjButton = new javax.swing.JButton();
        teachersjButton = new javax.swing.JButton();
        subjectsjButton = new javax.swing.JButton();
        studentjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        exitjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paymentsjButton.setText("Payments");
        paymentsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(paymentsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 40));

        teachersjButton.setText("Teachers");
        teachersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(teachersjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 40));

        subjectsjButton.setText("Subjects");
        subjectsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectsjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(subjectsjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 40));

        studentjButton.setText("Students");
        studentjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/moocs (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(1280, 600));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 0, 680, 375));

        exitjButton.setText("Exit");
        exitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectsjButtonActionPerformed
        SubjectJFrame subJF = new SubjectJFrame(SubjectJFrame.LAUNCHALONE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        subJF.setLocation(dim.width/2-subJF.getSize().width/2, dim.height/2-subJF.getSize().height/2);
        subJF.setVisible(true);
        subJF.setDefaultCloseOperation(subJF.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_subjectsjButtonActionPerformed

    private void studentjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentjButtonActionPerformed
        StudentJFrame sJF = new StudentJFrame();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        sJF.setLocation(dim.width/2-sJF.getSize().width/2, dim.height/2-sJF.getSize().height/2);
        sJF.setVisible(true);
        sJF.setDefaultCloseOperation(sJF.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_studentjButtonActionPerformed

    private void teachersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersjButtonActionPerformed
        TeacherJFrame tJF = new TeacherJFrame();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        tJF.setLocation(dim.width/2-tJF.getSize().width/2, dim.height/2-tJF.getSize().height/2);
        tJF.setVisible(true);
        tJF.setDefaultCloseOperation(tJF.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_teachersjButtonActionPerformed

    private void exitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjButtonActionPerformed
        LoginJFrame lJF = new LoginJFrame();
        lJF.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        lJF.setLocation(dim.width/2-lJF.getSize().width/2, dim.height/2-lJF.getSize().height/2);
    }//GEN-LAST:event_exitjButtonActionPerformed

    private void paymentsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsjButtonActionPerformed
        PaymentJFrame pJF = new PaymentJFrame();
        pJF.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        pJF.setLocation(dim.width/2-pJF.getSize().width/2, dim.height/2-pJF.getSize().height/2);
        pJF.setDefaultCloseOperation(pJF.DISPOSE_ON_CLOSE);                             
    }//GEN-LAST:event_paymentsjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitjButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton paymentsjButton;
    private javax.swing.JButton studentjButton;
    private javax.swing.JButton subjectsjButton;
    private javax.swing.JButton teachersjButton;
    // End of variables declaration//GEN-END:variables
}
